############################################################################### 
# Project Euler Problem 0002                                                  #
#                                                                             # 
# Each new term in the Fibonacci sequence is generated by adding the previous #
# two terms. By starting with 1 and 2, the first 10 terms will be:            #
#                                                                             #	
#	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                #
#                                                                             #	
# By considering the terms in the Fibonacci sequence whose values do not      #
# exceed four million, find the sum of the even-valued terms.                 #           
###############################################################################

# Tag start time
start_time = Time.now

# Variables
limit = 4000000
fib = 0
fib_prev1 = 1
fib_prev2 = 0
sum = 0

while fib <= limit
  fib = fib_prev1 + fib_prev2
  if fib % 2 == 0
    sum = sum + fib
  end
  fib_prev2 = fib_prev1
  fib_prev1 = fib
end

end_time = Time.now

puts "The answer is #{sum}."
puts "Elapsed time: #{((end_time - start_time)*1000).round(3)} milliseconds."
